### PR TITLE
Fixed point

### LINKED ISSUE #97: Fixed point quantity types
For lots of embedded systems or control applications there are significant benefits to employing fixed point arithmetic. Comments are welcome on the following proposal of how `dimensional` can be modified to ease development and ensure correctness of such applications.

This is usually done the same way dimensions are usually tracked, e.g. simply through comments or convention. To give an example (and I'm not picking on smaccmpilot, those guys are great, just showing theirs because the source is available) there is a lot of stuff like this: https://github.com/GaloisInc/smaccmpilot-stm32f4/blob/d14ca1c8507194727f37f9510a9197f19d20cac1/src/smaccm-comm-schema/smaccm-comm-schema.gidl#L144

```
(def-struct position_sample_t
  (fix         gps_fix_t)
  (num_sv      uint8_t) -- number of space vehicles
  (dop         float_t) -- estimated dilution of precision, meters
  (lat         sint32_t) -- degrees * 1e7
  (lon         sint32_t) -- degrees * 1e7
  (alt         sint32_t) -- meters * 1000 (aka mm)
  (vnorth      sint32_t) -- m/s * 100 (aka cm/s)
  (veast       sint32_t) -- m/s * 100 (aka cm/s)
  (vdown       sint32_t) -- m/s * 100 (aka cm/s)
  (vground     uint32_t) -- m/s * 100 (aka cm/s)
  (heading     float_t) -- degrees
  (time        time_micros_t))
```

Now, `dimensional` solves the issue of dimension tracking and unit conversion, but in its current form it essentially only does so for types with at least a `Fractional` context and in some cases even a `Floating` context is required, because the conversion factors involved to the coherent SI unit are rarely integers.

I'd like to solve this by introducing types with statically tracked but dynamically erased conversion factors to the coherent SI unit. This is what the standard approach does, but because the conversion factors are only tracked by comments you have to remember them whenever you perform arithmetic operations. Referring back to the above example, if you want to estimate what your altitude will be in a little while, you can't do `alt - deltat * vdown`, instead you have to do (assuming `deltat` is in microseconds because `time` appears to be) `alt - 100000 * deltat * vdown` (because `1 mm  / (1 cm/s * 1 us) = 100000`) and the burden on you is to remember and to work out what the number should be.

My initial design idea for this was to introduce a new constructor to the `Variant` data kind, changing it from:

```
data Variant = DQuantity         -- ^ The value is a quantity.
             | DUnit Metricality -- ^ The value is a unit, possibly a 'Metric' unit.
```

to something like:

```
data Variant = DQuantity         -- ^ The value is a quantity.
             | SQuantity ExactPi' -- ^ The value is a quantity scaled by a type-level exact rational multiple of an integer power of pi.
             | DUnit Metricality -- ^ The value is a unit, possibly a 'Metric' unit.
```

I got partway down this road and I now feel it to be a mistake. The reason is because you can express the semantics of `DQuantity` as `SQuantity One`. So I now prefer a design like:

```
data Variant = DQuantity ExactPi' -- ^ The value is a quantity scaled by a type-level exact rational multiple of an integer power of pi.
             | DUnit Metricality -- ^ The value is a unit, possibly a 'Metric' unit.
```

We can recover the existing `Quantity` type through type synonyms, changing `type Quantity d a = Dimensional 'DQuantity d a` to:

```
type SQuantity s d a = Dimensional ('DQuantity s) d a
type Quantity = SQuantity One
```

Our current multiplication operation uses this type family and operator:

```
-- | Forms the product of two 'Variant's.
--
-- The product of units is a non-metric unit.
--
-- The product of quantities is a quantity.
type family (v1 :: Variant) * (v2 :: Variant) :: Variant where
  'DUnit m1  * 'DUnit m2  = 'DUnit 'NonMetric
  'DQuantity * 'DQuantity = 'DQuantity

(*) :: (..., Num a) => Dimensional v1 d1 a -> Dimensional v2 d2 a -> Dimensional (v1 V.* v2) (d1 * d2) a
(*) = ...
```

With this design, the type of a product is uniquely determined by the type of the operands. This is probably a desirable property to keep to avoid introducing a lot of meaningless ambiguity into existing programs. So I propose changing the type family to either:

```
type family (v1 :: Variant) * (v2 :: Variant) :: Variant where
  'DUnit m1  * 'DUnit m2  = 'DUnit 'NonMetric
  'DQuantity v1 * 'DQuantity v2 = 'DQuantity One
```

or:

```
type family (v1 :: Variant) * (v2 :: Variant) :: Variant where
  'DUnit m1  * 'DUnit m2  = 'DUnit 'NonMetric
  'DQuantity v1 * 'DQuantity v2 = 'DQuantity (v1 E.* v2) -- where E is the type-level exact pi module
```

In the first design, whenever you multiply you are always going to normalize the result, so the `(*)` operation would need a `Floating` context instead of a `Num` one. In the second design, whenever you multiply you are going to multiply scale factors, so we can keep the `Num` context. In either case, the type synonyms proposed above will lead to the exact same behavior for all `Quantity` types.

I am leaning towards the second design because of the weaker context.

Under either design branch, we would introduce something else like:

```
approxproduct :: (..., Num a, Integral a) => SQuantity v1 d1 a -> SQuantity v2 d2 a -> SQuantity v3 (d1 * d2) a
approxproduct = ...
```

`approxproduct` would perform the multiplication considering all the scale factors, including the scale factor of the result which (crucially) is determined here from context and not from the scale factors of the operands, and round to the nearest representable result. I'm not exactly sure what type it would use for the intermediate value, so there might need to be multiple flavors that either do it through `Rational` or `Double` or by rounding the conversion factor and just doing integer arithmetic. (The third one may be the preferable default for most applications?)

Now if `alt :: SQuantity [exact| 1 / 1000] DLength Int32` and `vdown :: SQuantity [exact 1/100] DVelocity Int32` and `deltat :: SQuantity [exact| 1000000] DTime Int32`, and we have aliased `approxproduct` as `(*)` then `alt - deltat * vdown` will Do The Right Thing with a static guarantee. (Imagine that `exact` is a quasiquoter for type-level exact pi types.) (With a quasiquoter that could parse unit names, this could be easier to read and to write.)

### PR DESCRIPTION
**Pull request by dmcclean**
Submitted for review, the 'Numeric.Units.Dimensional.FixedPoint' module.

It offers almost exactly the same exports as 'Numeric.Units.Dimensional', but with different types. Instead of anticipating that users will generally use `Quantity d a` values with at least a `Fractional a` context, this module anticipates that users will generally use `SQuantity s d a` values with an `Integral a` context.

A value of type `SQuantity s d a` is a newtype wrapper around an `a` value that represents that value times the term-level equivalent of the type-level `ExactPi` value `s` in the coherent SI unit of dimension `d`. The previous `Quantity` type is recovered as a special case, `type Quantity = SQuantity One`.

The use of type-level `ExactPi` values instead of type-level rationals allows the representation of types that store an exact rational fraction of a `revolution`, including the ability to compute trigonometric functions of such values by performing an exact integer modulus instead of a floating point modulus.

Fixes #97.

Comment period through 10 January 2015 at the least.

### CODE REVIEW

File: src/Numeric/Units/Dimensional/Variants.hs [hunk 1]
```diff
@@ -68,9 +69,21 @@ infixl 7  *
 -- The product of quantities is a quantity.
 type family (v1 :: Variant) * (v2 :: Variant) :: Variant where
   'DUnit m1  * 'DUnit m2  = 'DUnit 'NonMetric
-  'DQuantity * 'DQuantity = 'DQuantity 
+  'DQuantity s1 * 'DQuantity s2 = 'DQuantity (s1 E.* s2)
```
Comment (dmcclean) [inline src/Numeric/Units/Dimensional/Variants.hs:72]: This is a problem. Prior to fixed point, the types of multiplication and division both used the variant product, because they did the same thing. Now that quantities carry a scale factor, this doesn't work (even though it still typechecks) because the scale factor on the result won't be correct.

**Comment by dmcclean** [comment]
@bjornbm Could you take a brief look at this and see if you have any major objections?

I think it is ready (including haddocks) to go in the next release, and it's complicating my workflow to have projects that depend on this but also be working on developing other things for the next dimensional release in branches that don't have it.

**Comment by bjornbm** [comment]
Without digging too far into the details it looks well prepared. Let's wait for conclusion on the GHC 8 issues but otherwise I trust you to judge the readiness. Perhaps do a GHC 8 fix without FixedPoint followed by a(nother) major release with FixedPoint, unless there is too much doubling of effort?

**Comment by dmcclean** [comment]
Does 1.0.1.2 with just the GHC 8 fix (which is just syntactic and doesn't affect behavior or types), and 1.1 for the next big fix work for everyone? If so, I'll cherry pick the GHC 8 fix into the maintenance branch we have and release that this afternoon.

**Comment by bjornbm** [comment]
Which branches are you referring to? I can only find version 1.0.1.1 in the cabal files. Either way, all I am in a position to do would be to test building 1.0.1.2 and 1.1 on GHC 7.10.2.

**Comment by dmcclean** [comment]
The `maintenance` branch contains the code that is currently released on hackage as 1.0.1.1. I'm proposing cherry-picking this GHC 8 fix into that branch, bumping the version to 1.0.1.2, and releasing that with a changelog note that it works around the GHC 8 issue.

Separately, all this other work that is currently in master, this PR, and a few outstanding issues, will be released as 1.1 once we can finish polishing it.

**Comment by bjornbm** [comment]
Ah, I see. I misinterpreted you as having prepared a 1.0.1.2 branch and a 1.1 branch for testing ("work for everyone"), but understand now you were referring to the release strategy. Yes, what you propose works for me!

**Comment by dmcclean** [comment]
Poorly phrased, sorry. :)
